spring.datasource.url=jdbc:postgresql://postgres-auth:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.jpa.show-sql=false

logging.level.com.ecommerce.auth=INFO
logging.level.org.springframework.security=INFO