# DataSource
spring.datasource.url=jdbc:postgresql://postgres-catalog:5433/catalog_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# RabbitMQ
spring.rabbitmq.host=rabbitmq

# JPA
spring.jpa.show-sql=false