spring.application.name=api-gateway
app.security.public-paths=/auth/register,/auth/login,/actuator/**
server.port=8080

# JWT (apenas para validacao, nao gera token)
jwt.secret=3f8a2b1c9d4e7f6a0b5c8d2e1f4a7b3c9d6e2f5a8b1c4d7e0f3a6b9c2d5e8f1a

# Rotas
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=catalog-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://catalog-service:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/products/**

spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://order-service:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=Name=CircuitBreaker,Args[name=orderServiceCB,fallbackUri=forward:/fallback/orders]

spring.cloud.gateway.server.webflux.routes[3].id=payment-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://payment-service:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/payments/**

spring.cloud.gateway.server.webflux.routes[4].id=notification-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://notification-service:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/notifications/**

spring.cloud.gateway.server.webflux.routes[0].filters[1].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.redis-rate-limiter.burstCapacity=20

# Actuator
spring.cloud.gateway.actuator.verbose.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,prometheus,beans,env
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true